#!/usr/bin/env bash
./generate_map_scales.sh
./start &
xdg-open "http://127.0.0.1:1533/MathQuest/play.html"

echo "on the webpage type /installSw and press enter"
echo "then also click install in the browsers omibar to install it as a pwa"
echo "press enter when done to exit"
read -r _
kill %%
