const PROG_DATA = [
  {
    room: "20_20",
    requires: [["area:2"]],
    receive: ["loot:venom", "loot:bClaw"],
  },
  {
    room: "20_20",
    requires: [["area:12"]],
    receive: ["weapon:pitchfork"],
  },
  {
    room: "20_20",
    requires: [["area:8"]],
    receive: ["weapon:orcBlade"],
  },
  { room: "13_25", requires: [["area:13"]], receive: ["loot:mHat"] },
  { room: "20_20", requires: [["area:4"]], receive: ["loot:mStaff"] },
  {
    room: "20_20",
    requires: [["area:16"]],
    receive: ["loot:sTooth", "loot:vHorn"],
  },
  { room: "20_20", requires: [["area:2"]], receive: ["loot:bTooth"] },
  {
    room: "20_20",
    requires: [["area:15"]],
    receive: ["loot:cThread"],
  },
  {
    room: "20_20",
    requires: [["area:12"]],
    receive: ["loot:dScale"],
  },
  { room: "20_20", requires: [["area:8"]], receive: ["loot:oCoin"] },
  {
    room: "20_20",
    requires: [["area:15"]],
    receive: ["loot:shadowCrest"],
  },
  { room: "20_20", requires: [["area:1"]], receive: ["loot:bTusk"] },
  {
    room: "20_20",
    requires: [["area:11"]],
    receive: ["loot:kCrest"],
  },
  {
    room: "20_20",
    requires: [[]],
    receive: [
      "skill:dig",
      "skill:kick",
      "skill:flee",
      "skill:swap",
      "flag:magic only resist bypass",
      "skill:firewall",
      "skill:halo",
      "item:gold",
      "loot:key#999",
    ],
  },
  {
    room: "20_20",
    requires: [[]],
    receive: [
      "loot:cFang",
      "loot:emeralds",
      "loot:fBone",
      "loot:gSkin",
      "loot:gFeather",
      "loot:mHat",
      "loot:mHorn",
      "loot:sClaw",
      "loot:sFrag",
      "loot:oArm",
      "loot:tBand",
      "loot:vAsh",
      "loot:wPelt",
    ],
  },
  {
    room: "15_21",
    requires: [["entrance.west0"]],
    receive: ["food:banana#1"],
  },
  {
    room: "21_20",
    requires: [["loot:venom#1"]],
    receive: ["food:orange - #1"],
  },
  {
    room: "14_19",
    requires: [["loot:tBand#1", "entrance.north0"]],
    receive: ["loot:aClub#1"],
  },
  {
    room: "13_16",
    requires: [["loot:key#1", "entrance.west0"]],
    receive: ["weapon:sKnife"],
  },
  {
    room: "15_16",
    requires: [["permit:bomb", "loot:mStaff#20"]],
    receive: ["magic:ice"],
  },
  {
    room: "13_13",
    requires: [["armor:alphaArmor"]],
    receive: ["craft:upgradeAAHP", "craft:upgradeAAMP"],
  },
  {
    room: "11_13",
    requires: [["loot:mStaff#1"]],
    receive: ["food:blueberries#1"],
  },
  {
    room: "11_12",
    requires: [["item:gold#100"]],
    receive: ["food:sunflowerSeeds#1"],
  },
  {
    room: "12_12",
    requires: [["quest:rings.1", "entrance.west0"]],
    receive: ["misc:headstoneSwitch2"],
  },
  {
    room: "12_9",
    requires: [["item:gold"]],
    receive: ["food:cherries"],
  },
  {
    room: "12_9",
    requires: [["item:gold#1000"]],
    receive: ["weapon:sKnife"],
  },
  {
    room: "12_9",
    requires: [["item:gold#1600"]],
    receive: ["weapon:warlockStaff"],
  },
  {
    room: "12_9",
    requires: [["item:gold"]],
    receive: ["weapon:sunSword"],
  },
  {
    room: "12_9",
    requires: [["loot:venom"]],
    receive: ["food:orange"],
  },
  {
    room: "11_9",
    requires: [
      ["item:gold", "entrance.north0"],
      ["item:gold", "entrance.east0"],
    ],
    receive: ["magic:weak"],
  },
  {
    room: "11_9",
    requires: [
      ["loot:wPelt", "entrance.north0"],
      ["loot:wPelt", "entrance.east0"],
    ],
    receive: ["item:gold#22"],
  },
  {
    room: "5_9",
    requires: [
      ["loot:mHorn", "entrance.north0"],
      ["loot:mHorn", "entrance.east2"],
    ],
    receive: ["loot:aAxe#1"],
  },
  {
    room: "8_14",
    requires: [["loot:sTooth#30", "item:gold#800", "skill:tough"]],
    receive: ["skill:tough.+1"],
  },
  { room: "10_16", requires: [], receive: [] },
  {
    room: "9_16",
    requires: [["loot:gSkin#1"]],
    receive: ["item:gold#23"],
  },
  {
    room: "4_17",
    requires: [["weapon:axe", "loot:vHorn#2"]],
    receive: ["weapon:axe.+1"],
  },
  {
    room: "8_17",
    requires: [[]],
    receive: ["flag:green secret code"],
  },
  {
    room: "11_17",
    requires: [["loot:key#1", "permit:bomb"]],
    receive: ["item:bombs#8", "item:gold#200"],
  },
  {
    room: "7_18",
    requires: [["loot:slamstones#1", "skill:reveal"]],
    receive: ["skill:reveal.+1"],
  },
  {
    room: "20_20",
    requires: [["area:red chest"]],
    receive: ["loot:slamstones"],
  },
  {
    room: "7_25",
    requires: [["flag:magic:fire.2"]],
    receive: ["flag:lit torch 2"],
  },
  {
    room: "8_21",
    requires: [["flag:magic:fire.2"]],
    receive: ["flag:lit torch 1"],
  },
  {
    room: "9_22",
    requires: [["entrance.south0", "item:gold"]],
    receive: ["food:chocolate"],
  },
  {
    room: "9_22",
    requires: [["entrance.south0", "item:gold"]],
    receive: ["food:steak"],
  },
  {
    room: "9_22",
    requires: [["entrance.south0", "item:gold"]],
    receive: ["food:peppers"],
  },
  {
    room: "10_22",
    requires: [
      [
        "entrance.south1",
        "loot:aScepter#1",
        "loot:dScale#5",
        "skill:craft",
      ],
      [
        "entrance.south0",
        "loot:aScepter#1",
        "loot:dScale#5",
        "skill:craft",
        "permit:bomb.2",
      ],
    ],
    receive: ["craft:elixir"],
  },
  {
    room: "10_25",
    requires: [["quest:rings.1"]],
    receive: ["misc:headstoneSwitch3"],
  },
  {
    room: "100_100",
    requires: [["loot:oArm#5", "loot:sTooth#5", "loot:vHorn#5"]],
    receive: ["craft:newtonApple"],
  },
  {
    room: "11_22",
    requires: [["loot:sTooth#10", "skill:craft"]],
    receive: ["craft:emerald"],
  },
  {
    room: "12_25",
    requires: [["misc:blue crystal"]],
    receive: ["food:gummyBears#10", "item:diamonds - chest#50"],
  },
  {
    room: "13_25",
    requires: [["loot:mHat#1", "flag:magic only resist bypass"]],
    receive: ["loot:aScepter#1"],
  },
  {
    room: "14_25",
    requires: [],
    receive: ["flag:three part code part 1"],
  },
  {
    room: "14_24",
    requires: [],
    receive: ["flag:three part code part 2"],
  },
  {
    room: "13_24",
    requires: [],
    receive: ["flag:three part code part 3"],
  },
  {
    room: "13_26",
    requires: [
      [
        "flag:three part code part 1",
        "flag:three part code part 2",
        "flag:three part code part 3",
      ],
    ],
    receive: ["food:gingerBread#99"],
  },
  { room: "11_26", requires: [], receive: ["flag:stomp code"] },
  {
    room: "18_24",
    requires: [["quest:rings.1"]],
    receive: ["misc:headstoneSwitch4"],
  },
  {
    room: "21_23",
    requires: [["skill:dig"]],
    receive: ["item:diamonds - dig#2"],
  },
  {
    room: "21_22",
    requires: [["item:ring of gold", "loot:tBand#5", "loot:gSkin#2"]],
    receive: ["craft:ringGold"],
  },
  {
    room: "20_22",
    requires: [["item:gold#500"]],
    receive: ["item:rubies#1"],
  },
  {
    room: "20_23",
    requires: [["skill:reveal", "entrance.west0", "permit:bomb"]],
    receive: ["area:red chest"],
  },
  {
    room: "19_22",
    requires: [["loot:aAxe#5"]],
    receive: ["skill:reveal"],
  },
  {
    room: "19_21",
    requires: [["quest:dig.3", "loot:bTooth#1"]],
    receive: ["item:gold#18"],
  },
  { room: "19_20", requires: [[]], receive: ["quest:pam.1"] },
  {
    room: "21_20",
    requires: [["loot:bTusk#1"]],
    receive: ["item:gold#20"],
  },
  {
    room: "20_18",
    requires: [["quest:rings.11"]],
    receive: ["quest:rings.12"],
  },
  {
    room: "21_18",
    requires: [["loot:emeralds#1"]],
    receive: ["item:diamonds#Enum.Craft.emerald", "food:peppers#30"],
  },
  {
    room: "21_17",
    requires: [["item:gold#500"]],
    receive: ["item:rubies#1"],
  },
  {
    room: "20_15",
    requires: [["loot:dScale#5", "loot:medallions#3"]],
    receive: ["skill:firewall.2", "flag:skill.firewall checked.2"],
  },
  {
    room: "20_15",
    requires: [
      [
        "loot:dScale#10",
        "flag:skill.firewall checked.2",
        "loot:medallions#6",
      ],
    ],
    receive: ["skill:firewall.3", "flag:skill.firewall checked.3"],
  },
  {
    room: "20_15",
    requires: [
      [
        "flag:skill.firewall checked.3",
        "loot:dScale#15",
        "loot:medallions#9",
      ],
    ],
    receive: ["skill:firewall.4", "flag:skill.firewall checked.4"],
  },
  {
    room: "20_15",
    requires: [
      [
        "flag:skill.firewall checked.4",
        "loot:dScale#20",
        "loot:medallions#12",
      ],
    ],
    receive: ["skill:firewall.5", "flag:skill.firewall checked.5"],
  },
  {
    room: "20_15",
    requires: [
      [
        "flag:skill.firewall checked.5",
        "loot:dScale#25",
        "loot:medallions#15",
      ],
    ],
    receive: ["skill:firewall.6", "flag:skill.firewall checked.6"],
  },
  {
    room: "20_15",
    requires: [
      [
        "flag:skill.firewall checked.6",
        "loot:dScale#30",
        "loot:medallions#18",
      ],
    ],
    receive: ["skill:firewall.7", "flag:skill.firewall checked.7"],
  },
  {
    room: "20_15",
    requires: [
      [
        "flag:skill.firewall checked.7",
        "loot:dScale#35",
        "loot:medallions#21",
      ],
    ],
    receive: ["skill:firewall.8", "flag:skill.firewall checked.8"],
  },
  {
    room: "20_15",
    requires: [
      [
        "flag:skill.firewall checked.8",
        "loot:dScale#40",
        "loot:medallions#24",
      ],
    ],
    receive: ["skill:firewall.9", "flag:skill.firewall checked.9"],
  },
  {
    room: "20_15",
    requires: [
      [
        "flag:skill.firewall checked.9",
        "loot:dScale#45",
        "loot:medallions#27",
      ],
    ],
    receive: ["skill:firewall.10", "flag:skill.firewall checked.10"],
  },
  {
    room: "19_15",
    requires: [["loot:medallions#20"]],
    receive: ["item:rubies#1"],
  },
  {
    room: "19_15",
    requires: [["loot:medallions#3"]],
    receive: ["skill:hint"],
  },
  {
    room: "19_15",
    requires: [["loot:medallions#30"]],
    receive: ["skill:fear"],
  },
  {
    room: "16_16",
    requires: [["quest:rings.1"]],
    receive: ["misc:headstoneSwitch1"],
  },
  {
    room: "18_13",
    requires: [
      ["loot:cThread#10", "loot:shadowCrest#5", "skill:reveal"],
    ],
    receive: ["misc:bombCapacity"],
  },
  {
    room: "24_11",
    requires: [["loot:key#1", "permit:bomb"]],
    receive: ["weapon:baneBlade"],
  },
  {
    room: "100_100",
    requires: [["loot:sTooth#5", "loot:vHorn#5", "loot:oArm#5"]],
    receive: ["craft:newtonsApple"],
  },
  {
    room: "11_15",
    requires: [["skill:craft", "loot:tBand#5", "loot:wPelt#2"]],
    receive: ["craft:key"],
  },
  { room: "18_19", requires: [[]], receive: ["quest:gTree.1"] },
  { room: "21_20", requires: [[]], receive: ["quest:bBomb.1"] },
  { room: "19_21", requires: [[]], receive: ["quest:dig.1"] },
  {
    room: "19_21",
    requires: [["skill:dig", "quest:dig.1"]],
    receive: ["quest:dig.2"],
  },
  {
    room: "19_21",
    requires: [["quest:dig.2", "skill:dig"]],
    receive: ["quest:dig.3", "item:gold - dig2#25"],
  },
  {
    room: "21_20",
    requires: [["food:honey#10"]],
    receive: ["magic:crush"],
  },
  {
    room: "21_20",
    requires: [["quest:gTree.1"]],
    receive: ["quest:gTree.2"],
  },
  {
    room: "18_22",
    requires: [["quest:gTree.2"]],
    receive: ["quest:gTree.3"],
  },
  {
    room: "19_23",
    requires: [["loot:bTooth#15", "quest:gTree.3"]],
    receive: ["quest:gTree.4"],
  },
  {
    room: "18_19",
    requires: [["quest:gTree.4"]],
    receive: ["quest:gTree.5"],
  },
  {
    room: "21_20",
    requires: [["quest:gTree.5"]],
    receive: ["quest:gTree.6", "item:gold#50"],
  },
  {
    room: "14_20",
    requires: [["quest:gTree.6"]],
    receive: ["quest:gTree.7"],
  },
  {
    room: "15_23",
    requires: [["quest:pam.1", "skill:dig"]],
    receive: ["quest:pam.2"],
  },
  {
    room: "19_20",
    requires: [["quest:pam.2"]],
    receive: ["quest:pam.3", "item:gold - pam2#20"],
  },
  {
    room: "12_20",
    requires: [["quest:pam.3"]],
    receive: ["quest:pam.4"],
  },
  {
    room: "19_20",
    requires: [["quest:pam.4"]],
    receive: ["quest:pam.5", "food:gingerBread - pam4#10"],
  },
  {
    room: "14_18",
    requires: [["quest:gTree.7"]],
    receive: ["quest:gTree.8"],
  },
  {
    room: "14_18",
    requires: [["quest:gTree.8"]],
    receive: ["quest:gTree.9"],
  },
  { room: "17_19", requires: [[]], receive: ["quest:oMan.1"] },
  {
    room: "21_21",
    requires: [["food:honey#5", "loot:venom#1"]],
    receive: ["skill:craft"],
  },
  {
    room: "16_14",
    requires: [["quest:gTree.9"]],
    receive: ["quest:gTree.10"],
  },
  {
    room: "15_18",
    requires: [["quest:gTree.10"]],
    receive: ["quest:gTree.11", "food:beefJerky#3"],
  },
  {
    room: "13_21",
    requires: [["quest:bBomb.1", "entrance.south0"]],
    receive: ["quest:bBomb.2"],
  },
  {
    room: "21_20",
    requires: [["quest:bBomb.2"]],
    receive: ["quest:bBomb.3"],
  },
  {
    room: "13_21",
    requires: [["quest:bBomb.3", "entrance.south0"]],
    receive: ["quest:bBomb.4", "permit:bomb", "craft:bomb"],
  },
  {
    room: "10_17",
    requires: [["quest:pam.5"]],
    receive: ["quest:pam.6"],
  },
  {
    room: "19_20",
    requires: [["quest:pam.6"]],
    receive: ["quest:pam.7", "food:chocolate#5"],
  },
  {
    room: "10_19",
    requires: [["quest:gTree.11"]],
    receive: ["quest:gTree.12"],
  },
  {
    room: "15_18",
    requires: [["quest:gTree.12"]],
    receive: ["quest:gTree.13"],
  },
  {
    room: "12_14",
    requires: [["quest:bBomb.4"]],
    receive: ["quest:bBomb.5"],
  },
  {
    room: "9_11",
    requires: [["quest:pam.7", "entrance.south1"]],
    receive: ["quest:pam.8"],
  },
  {
    room: "12_9",
    requires: [["quest:gTree.13"]],
    receive: ["quest:gTree.14"],
  },
  {
    room: "12_9",
    requires: [["quest:gTree.14", "loot:sClaw#7", "loot:cFang#5"]],
    receive: ["quest:gTree.15", "misc:fire crystal"],
  },
  {
    room: "11_9",
    requires: [["entrance.north0"], ["entrance.east0"]],
    receive: ["quest:warp.1"],
  },
  {
    room: "12_11",
    requires: [["entrance.west0"], ["entrance.south0"]],
    receive: ["quest:canteen.1"],
  },
  { room: "8_9", requires: [["misc:fire crystal"]], receive: [] },
  {
    room: "7_11",
    requires: [["quest:gTree.15"]],
    receive: ["quest:gTree.16", "flag:7_11 boss dead"],
  },
  {
    room: "7_10",
    requires: [
      ["quest:gTree.16", "permit:bomb", "flag:7_11 boss dead"],
    ],
    receive: ["quest:gTree.17"],
  },
  {
    room: "15_18",
    requires: [["quest:gTree.17"]],
    receive: ["quest:gTree.18", "permit:shadowsoulEntrance"],
  },
  {
    room: "9_22",
    requires: [["entrance.south0"]],
    receive: ["quest:seeds.1"],
  },
  { room: "6_23", requires: [[]], receive: [] },
  {
    room: "5_24",
    requires: [["quest:gTree.18"]],
    receive: ["quest:gTree.19", "food:holyWater#1"],
  },
  {
    room: "5_24",
    requires: [["quest:gTree.19"]],
    receive: ["quest:gTree.20"],
  },
  {
    room: "15_18",
    requires: [["quest:gTree.20"]],
    receive: ["quest:gTree.21"],
  },
  {
    room: "16_14",
    requires: [["quest:gTree.21"]],
    receive: ["quest:gTree.22"],
  },
  {
    room: "24_9",
    requires: [["quest:gTree.22"]],
    receive: ["quest:gTree.23", "flag:final boss dead"],
  },
  {
    room: "24_9",
    requires: [["quest:gTree.23"]],
    receive: ["quest:gTree.24"],
  },
  {
    room: "14_18",
    requires: [["quest:gTree.24"]],
    receive: ["quest:gTree.25", "misc:pup#10", "item:gold#1000"],
  },
  {
    room: "14_18",
    requires: [["quest:gTree.25"]],
    receive: ["quest:aSword.1"],
  },
  {
    room: "15_24",
    requires: [["quest:oMan.1"]],
    receive: ["quest:oMan.2"],
  },
  {
    room: "17_19",
    requires: [["quest:oMan.2"]],
    receive: ["quest:oMan.3"],
  },
  {
    room: "11_21",
    requires: [["quest:oMan.3"]],
    receive: ["quest:oMan.4"],
  },
  {
    room: "10_15",
    requires: [["quest:oMan.4"]],
    receive: ["quest:oMan.5"],
  },
  {
    room: "12_11",
    requires: [["quest:canteen.2"]],
    receive: ["quest:canteen.3", "item:diamonds#1"],
  },
  { room: "14_22", requires: [[]], receive: ["quest:rings.1"] },
  {
    room: "14_22",
    requires: [["quest:rings.1", "skill:dig"]],
    receive: ["item:ring of gold"],
  },
  {
    room: "14_22",
    requires: [["quest:rings.1", "item:ring of gold"]],
    receive: ["quest:rings.2"],
  },
  {
    room: "16_21",
    requires: [["skill:dig", "quest:rings.1"]],
    receive: ["item:ring of health"],
  },
  {
    room: "14_22",
    requires: [
      ["item:ring of gold", "item:ring of health", "quest:rings.1"],
    ],
    receive: ["quest:rings.3"],
  },
  {
    room: "14_22",
    requires: [
      [
        "item:ring of gold",
        "item:ring of health",
        "item:ring of evasion",
        "quest:rings.1",
      ],
    ],
    receive: ["quest:rings.4"],
  },
  {
    room: "13_16",
    requires: [["quest:rings.1", "entrance.south0", "permit:bomb"]],
    receive: ["item:ring of evasion"],
  },
  {
    room: "11_9",
    requires: [
      [
        "quest:warp.1",
        "misc:headstoneSwitch1",
        "misc:headstoneSwitch2",
        "misc:headstoneSwitch3",
        "misc:headstoneSwitch4",
        "entrance.north0",
      ],
      [
        "quest:warp.1",
        "misc:headstoneSwitch1",
        "misc:headstoneSwitch2",
        "misc:headstoneSwitch3",
        "misc:headstoneSwitch4",
        "entrance.east0",
      ],
    ],
    receive: ["quest:warp.2", "skill:warp"],
  },
  {
    room: "13_21",
    requires: [["quest:bBomb.5"]],
    receive: ["quest:bBomb.6", "permit:volcano"],
  },
  {
    room: "17_17",
    requires: [["quest:bBomb.6"]],
    receive: ["quest:bBomb.7"],
  },
  {
    room: "20_18",
    requires: [["quest:bBomb.7"]],
    receive: ["quest:bBomb.8"],
  },
  {
    room: "13_21",
    requires: [["quest:bBomb.8"]],
    receive: ["quest:bBomb.9", "permit:bomb.2"],
  },
  {
    room: "19_20",
    requires: [["quest:pam.8"]],
    receive: ["quest:pam.9"],
  },
  {
    room: "18_19",
    requires: [["quest:seeds.1"]],
    receive: ["quest:seeds.2"],
  },
  {
    room: "18_19",
    requires: [["quest:seeds.2", "loot:oCoin#20"]],
    receive: ["quest:seeds.3"],
  },
  {
    room: "9_22",
    requires: [["quest:seeds.3", "entrance.south0"]],
    receive: [
      "quest:seeds.4",
      "food:orange#10",
      "food:peppers - seeds3#3",
    ],
  },
  {
    room: "11_11",
    requires: [
      ["quest:rings.4", "entrance.north0"],
      ["quest:rings.4", "entrance.west0"],
    ],
    receive: ["quest:rings.5"],
  },
  {
    room: "11_11",
    requires: [["quest:rings.5"]],
    receive: ["quest:rings.6", "item:ring of poison"],
  },
  {
    room: "14_22",
    requires: [
      [
        "item:ring of gold",
        "item:ring of health",
        "item:ring of evasion",
        "item:ring of poison",
        "quest:rings.1",
      ],
    ],
    receive: ["quest:rings.7"],
  },
  {
    room: "16_15",
    requires: [["quest:pam.9", "skill:dig"]],
    receive: ["quest:pam.10"],
  },
  {
    room: "19_20",
    requires: [["quest:pam.10"]],
    receive: ["quest:pam.11", "food:peppers#5", "food:orange#20"],
  },
  {
    room: "15_16",
    requires: [["quest:rings.7", "permit:bomb"]],
    receive: ["quest:rings.8"],
  },
  {
    room: "15_16",
    requires: [["quest:rings.8"]],
    receive: ["item:ring of magic", "quest:rings.9"],
  },
  {
    room: "14_22",
    requires: [["quest:rings.9"]],
    receive: ["quest:rings.10"],
  },
  {
    room: "19_18",
    requires: [["quest:rings.10"]],
    receive: ["quest:rings.11"],
  },
  {
    room: "20_18",
    requires: [
      [
        "quest:rings.13",
        "loot:sFrag#5",
        "loot:dScale#3",
        "loot:fBone#10",
      ],
    ],
    receive: ["quest:rings.14"],
  },
  { room: "6_12", requires: [[]], receive: ["quest:geo.1"] },
  {
    room: "6_12",
    requires: [["quest:geo.1", "item:geode#5"]],
    receive: ["quest:geo.2"],
  },
  {
    room: "6_12",
    requires: [["quest:geo.2"]],
    receive: ["quest:geo.3"],
  },
  {
    room: "21_20",
    requires: [["quest:geo.3"]],
    receive: ["quest:geo.4"],
  },
  {
    room: "6_12",
    requires: [["quest:geo.4"]],
    receive: ["quest:geo.5", "skill:convert"],
  },
  {
    room: "6_12",
    requires: [["quest:rings.12", "quest:geo.5", "item:gold#1000"]],
    receive: ["quest:rings.13"],
  },
  { room: "19_16", requires: [[]], receive: ["loot:medallions"] },
  {
    room: "18_20",
    requires: [["loot:key"]],
    receive: ["item:gold#30"],
  },
  {
    room: "18_19",
    requires: [["loot:emeralds#1"]],
    receive: ["item:gold#Enum.Craft.emerald"],
  },
  {
    room: "17_20",
    requires: [["loot:key#1"]],
    receive: ["item:gold#200", "food:beefJerky#5"],
  },
  {
    room: "15_19",
    requires: [["skill:reveal", "permit:bomb"]],
    receive: ["area:red chest"],
  },
  {
    room: "15_19",
    requires: [["loot:key#1", "permit:bomb"]],
    receive: ["item:gold#300", "item:bombs#10", "food:banana#5"],
  },
  {
    room: "14_19",
    requires: [["loot:key#1", "entrance.south0"]],
    receive: ["armor:regenArmor"],
  },
  {
    room: "11_19",
    requires: [["loot:key#1", "entrance.east2"]],
    receive: ["food:sunflowerSeeds#1", "food:strawberry#1"],
  },
  {
    room: "8_18",
    requires: [["loot:emeralds#1", "entrance.north0"]],
    receive: ["item:bombs#25", "food:steak#Enum.Craft.emerald"],
  },
  {
    room: "11_18",
    requires: [["loot:key#1"]],
    receive: ["magic:refresh#1"],
  },
  {
    room: "15_18",
    requires: [
      ["misc:blue crystal", "permit:bomb.2", "quest:gTree.10"],
    ],
    receive: ["food:chocolate#20", "item:bombs#50"],
  },
  {
    room: "19_18",
    requires: [["misc:blue crystal"]],
    receive: ["item:rubies#3"],
  },
  {
    room: "19_17",
    requires: [
      ["skill:reveal", "entrance.south1"],
      ["skill:reveal", "entrance.east0"],
    ],
    receive: ["area:red chest"],
  },
  {
    room: "18_17",
    requires: [["loot:key#1", "entrance.north1"]],
    receive: ["item:gold#1000"],
  },
  {
    room: "13_16",
    requires: [["loot:key#1", "entrance.south0"]],
    receive: ["magic:weak"],
  },
  {
    room: "17_16",
    requires: [["loot:key#1"]],
    receive: ["item:diamonds#5"],
  },
  {
    room: "18_15",
    requires: [["misc:blue crystal"]],
    receive: ["food:newtonsApple#15"],
  },
  {
    room: "17_15",
    requires: [["loot:emeralds#1"]],
    receive: [
      "item:gold#100",
      "food:gingerBread#50",
      "item:gold#Enum.Craft.emerald",
    ],
  },
  {
    room: "16_15",
    requires: [["misc:blue crystal"]],
    receive: ["armor:diamondArmor", "quest:pam.16"],
  },
  {
    room: "19_20",
    requires: [["quest:pam.16"]],
    receive: ["food:gingerBread - pam16"],
  },
  {
    room: "14_15",
    requires: [["loot:key#1"]],
    receive: ["food:orange#12", "item:bombs#5"],
  },
  {
    room: "9_15",
    requires: [["loot:key#1"]],
    receive: ["armor:phantomCoat"],
  },
  {
    room: "5_15",
    requires: [["skill:reveal"]],
    receive: ["area:red chest"],
  },
  {
    room: "14_14",
    requires: [["skill:reveal"]],
    receive: ["area:red chest"],
  },
  {
    room: "15_14",
    requires: [
      ["loot:key#1", "entrance.east0"],
      ["loot:key#1", "permit:bomb"],
    ],
    receive: ["food:carrot#5"],
  },
  {
    room: "23_10",
    requires: [["loot:emeralds#1"]],
    receive: ["armor:alphaArmor"],
  },
  {
    room: "23_10",
    requires: [["loot:key#1"]],
    receive: ["item:diamonds#5", "food:newtonsApple#2"],
  },
  {
    room: "21_11",
    requires: [["loot:key#1", "entrance.north0"]],
    receive: ["food:gummyBears#5"],
  },
  {
    room: "23_13",
    requires: [["skill:reveal"]],
    receive: ["area:red chest"],
  },
  {
    room: "24_14",
    requires: [["loot:key#1"]],
    receive: ["armor:grimGear"],
  },
  {
    room: "10_13",
    requires: [["permit:bomb", "item:gold#500", "skill:reveal"]],
    receive: ["misc:ninja"],
  },
  {
    room: "10_13",
    requires: [["loot:emeralds#1"]],
    receive: [
      "item:gold#1",
      "item:diamonds#1",
      "item:aurastones#1",
      "loot:slamstones#1",
      "food:elixir#1",
      "food:holyWater#1",
    ],
  },
  {
    room: "9_13",
    requires: [["loot:key#1"]],
    receive: ["item:bombs#10"],
  },
  {
    room: "19_20",
    requires: [["quest:pam.12"]],
    receive: ["food:holyWater#1"],
  },
  {
    room: "6_13",
    requires: [["loot:key#1"]],
    receive: ["food:grapes#5", "food:strawberry#1"],
  },
  {
    room: "6_12",
    requires: [["loot:key#1"]],
    receive: ["item:geode#2"],
  },
  {
    room: "12_12",
    requires: [
      ["misc:blue crystal", "entrance.east1"],
      ["misc:blue crystal", "entrance.south0"],
    ],
    receive: ["magic:blessing"],
  },
  {
    room: "8_10",
    requires: [
      ["skill:reveal", "entrance.east2"],
      ["skill:reveal", "entrance.west0"],
      ["skill:reveal", "entrance.north0"],
    ],
    receive: ["area:red chest"],
  },
  {
    room: "8_10",
    requires: [
      ["loot:emeralds#1", "entrance.north1"],
      ["loot:emeralds#1", "entrance.east1"],
      ["loot:emeralds#1", "entrance.east2"],
    ],
    receive: ["item:gold#Enum.Craft.emerald", "food:beefJerky#30"],
  },
  {
    room: "9_10",
    requires: [["loot:key#1", "permit:bomb"]],
    receive: ["item:gold#750"],
  },
  {
    room: "10_9",
    requires: [["loot:key#1", "permit:bomb.2"]],
    receive: ["food:steak#30"],
  },
  {
    room: "6_10",
    requires: [["loot:key#1", "permit:bomb"]],
    receive: ["food:chocolate#3"],
  },
  {
    room: "18_21",
    requires: [["loot:key#1"]],
    receive: ["item:gingerBread#5"],
  },
  {
    room: "15_21",
    requires: [["loot:key#1", "entrance.south0"]],
    receive: ["item:gold#manager.fame * 5", "item:bombs#5"],
  },
  {
    room: "14_21",
    requires: [
      ["loot:key#1", "entrance.north0"],
      ["loot:key#1", "permit:bomb"],
    ],
    receive: ["item:gold#100", "item:bombs#12", "food:apple#30"],
  },
  {
    room: "12_21",
    requires: [["loot:emeralds#1", "permit:bomb"]],
    receive: ["item:diamonds#Enum.Craft.emerald", "food:banana#20"],
  },
  {
    room: "11_21",
    requires: [["loot:key#1"]],
    receive: ["item:bombs#15"],
  },
  {
    room: "9_22",
    requires: [["loot:key#1", "entrance.north0"]],
    receive: ["magic:doubleDown"],
  },
  {
    room: "16_22",
    requires: [["loot:key#1"]],
    receive: ["item:gold#400"],
  },
  {
    room: "17_22",
    requires: [["misc:blue crystal"]],
    receive: ["item:diamonds#20"],
  },
  {
    room: "21_23",
    requires: [["loot:key#1"]],
    receive: ["item:gold#300", "item:diamonds - chest#2"],
  },
  {
    room: "19_23",
    requires: [["loot:key#1"]],
    receive: ["magic:fire"],
  },
  {
    room: "18_23",
    requires: [["permit:bomb", "loot:key#1"]],
    receive: ["weapon:warlockStaff"],
  },
  {
    room: "9_23",
    requires: [["loot:key#1", "permit:bomb"]],
    receive: ["magic:drain"],
  },
  {
    room: "4_24",
    requires: [["loot:key#1", "entrance.east0"]],
    receive: ["food:cherries#10"],
  },
  {
    room: "6_24",
    requires: [["skill:reveal"]],
    receive: ["area:red chest"],
  },
  {
    room: "15_24",
    requires: [["loot:key#1", "entrance.north0"]],
    receive: ["item:gold#correct"],
  },
  {
    room: "16_24",
    requires: [["misc:blue crystal", "entrance.north0"]],
    receive: ["item:gold#1000", "food:gummyBears#12"],
  },
  {
    room: "16_25",
    requires: [
      ["misc:blue crystal", "entrance.south0"],
      ["misc:blue crystal", "entrance.west0"],
    ],
    receive: ["item:diamonds#5", "food:steak#12"],
  },
  {
    room: "11_25",
    requires: [["misc:blue crystal"]],
    receive: ["food:beefJerky#20"],
  },
  {
    room: "3_26",
    requires: [["misc:blue crystal"]],
    receive: ["food:elixir#1"],
  },
  {
    room: "4_26",
    requires: [
      ["permit:bomb", "entrance.south3", "loot:key#1"],
      ["permit:bomb", "entrance.south1", "loot:key#1"],
      ["permit:bomb", "entrance.south0", "loot:key#1"],
    ],
    receive: ["weapon:shadowStaff"],
  },
  {
    room: "9_26",
    requires: [["loot:key#1"]],
    receive: ["food:blueberries#10"],
  },
  {
    room: "16_18",
    requires: [["quest:bBomb.13"]],
    receive: ["quest:bBomb.25"],
  },
  {
    room: "11_16",
    requires: [["quest:dream.6"]],
    receive: ["quest:dream.7"],
  },
  {
    room: "16_10",
    requires: [["quest:rings.15"]],
    receive: ["quest:rings.16", "item:ring of death"],
  },
  {
    room: "17_10",
    requires: [["quest:hWater.4"]],
    receive: ["quest:hWater.5"],
  },
  {
    room: "11_16",
    requires: [["quest:oMan.5"]],
    receive: ["quest:oMan.6"],
  },
  {
    room: "10_15",
    requires: [["quest:canteen.1"]],
    receive: ["quest:canteen.2"],
  },
  {
    room: "10_15",
    requires: [["quest:canteen.3"]],
    receive: ["quest:canteen.4"],
  },
  {
    room: "21_17",
    requires: [["quest:oMan.19"]],
    receive: ["quest:oMan.20"],
  },
  {
    room: "11_23",
    requires: [["quest:dream.2"]],
    receive: ["quest:dream.3"],
  },
  { room: "14_17", requires: [[]], receive: ["quest:mChal.1"] },
  {
    room: "13_14",
    requires: [["quest:mChal.1"]],
    receive: ["quest:mChal.2"],
  },
  {
    room: "11_23",
    requires: [["quest:dream.3"]],
    receive: ["quest:dream.4"],
  },
  {
    room: "6_24",
    requires: [["quest:pam.11"]],
    receive: ["quest:pam.12"],
  },
  {
    room: "4_19",
    requires: [["quest:isles.3"]],
    receive: ["quest:isles.4"],
  },
  {
    room: "17_11",
    requires: [["quest:hWater.5"]],
    receive: ["quest:hWater.6"],
  },
  {
    room: "17_11",
    requires: [["quest:hWater.3"]],
    receive: ["quest:hWater.4"],
  },
  { room: "15_17", requires: [], receive: ["quest:hWater.1"] },
  {
    room: "15_17",
    requires: [["quest:hWater.6"]],
    receive: ["quest:hWater.7"],
  },
  {
    room: "16_15",
    requires: [["quest:hWater.1"]],
    receive: ["quest:hWater.2"],
  },
  {
    room: "19_20",
    requires: [["quest:pam.12"]],
    receive: ["quest:pam.13"],
  },
  {
    room: "19_20",
    requires: [["quest:pam.13"]],
    receive: ["quest:pam.14", "misc:blue crystal"],
  },
  {
    room: "19_20",
    requires: [["quest:pam.14"]],
    receive: ["quest:pam.15"],
  },
  {
    room: "14_17",
    requires: [["quest:mChal.2"]],
    receive: ["quest:mChal.3"],
  },
  { room: "19_16", requires: [], receive: ["quest:access.1"] },
  {
    room: "19_16",
    requires: [["quest:access.1"]],
    receive: ["quest:access.2"],
  },
  {
    room: "19_16",
    requires: [["quest:access.3"]],
    receive: ["quest:access.4"],
  },
  {
    room: "19_16",
    requires: [["quest:access.4"]],
    receive: ["quest:access.5"],
  },
  {
    room: "19_16",
    requires: [["quest:access.5"]],
    receive: ["quest:access.6"],
  },
  {
    room: "19_16",
    requires: [["quest:access.6"]],
    receive: ["quest:access.7"],
  },
  {
    room: "19_16",
    requires: [["quest:access.8"]],
    receive: ["quest:access.9"],
  },
  {
    room: "19_16",
    requires: [["quest:access.2"]],
    receive: ["quest:access.3"],
  },
  {
    room: "19_16",
    requires: [["quest:access.7"]],
    receive: ["quest:access.8"],
  },
  {
    room: "17_18",
    requires: [["quest:bBomb.9"]],
    receive: ["quest:bBomb.10"],
  },
  {
    room: "17_18",
    requires: [["quest:bBomb.12"]],
    receive: ["quest:bBomb.13"],
  },
  {
    room: "6_12",
    requires: [["quest:oMan.16"]],
    receive: ["quest:oMan.17"],
  },
  {
    room: "6_12",
    requires: [["quest:oMan.18"]],
    receive: ["quest:oMan.19"],
  },
  {
    room: "10_12",
    requires: [["quest:oMan.17"]],
    receive: ["quest:oMan.18"],
  },
  {
    room: "13_14",
    requires: [["quest:mChal.3"]],
    receive: ["quest:mChal.4"],
  },
  {
    room: "11_23",
    requires: [["quest:dream.4"]],
    receive: ["quest:dream.5"],
  },
  {
    room: "11_16",
    requires: [["quest:dream.7"]],
    receive: ["quest:dream.8"],
  },
  {
    room: "10_10",
    requires: [["quest:dream.8"]],
    receive: ["quest:dream.9"],
  },
  {
    room: "10_10",
    requires: [["quest:dream.9"]],
    receive: ["quest:dream.10"],
  },
  {
    room: "10_10",
    requires: [
      ["quest:dream.10", "entrance.north0"],
      ["quest:dream.10", "entrance.west0"],
    ],
    receive: ["quest:dream.11"],
  },
  {
    room: "11_16",
    requires: [["quest:dream.5"]],
    receive: ["quest:dream.6"],
  },
  { room: "100_100", requires: [], receive: ["quest:isles.1"] },
  {
    room: "100_100",
    requires: [["item:gold#25"]],
    receive: ["food:orange"],
  },
  {
    room: "100_100",
    requires: [["item:gold#10"]],
    receive: ["food:gingerBread"],
  },
  {
    room: "100_100",
    requires: [["item:gold#10"]],
    receive: ["food:gingerBread"],
  },
  {
    room: "100_100",
    requires: [["item:gold#100"]],
    receive: ["food:strawberry"],
  },
  {
    room: "100_100",
    requires: [["quest:isles.16"]],
    receive: ["quest:isles.17"],
  },
  {
    room: "4_26",
    requires: [["quest:isles.18"]],
    receive: ["quest:isles.19"],
  },
  {
    room: "4_26",
    requires: [
      ["quest:isles.19", "area:17", "area:6", "area:9", "area:2"],
    ],
    receive: ["quest:isles.22"],
  },
  {
    room: "201_200",
    requires: [["quest:isles.2"]],
    receive: ["quest:isles.3"],
  },
  {
    room: "201_200",
    requires: [["quest:isles.4"]],
    receive: ["quest:isles.5"],
  },
  {
    room: "201_200",
    requires: [["quest:isles.7"]],
    receive: ["quest:isles.8"],
  },
  {
    room: "201_200",
    requires: [["quest:isles.14"]],
    receive: ["quest:isles.15"],
  },
  {
    room: "300_300",
    requires: [["item:gold#1000", "loot:oCoin#10"]],
    receive: ["food:elixir"],
  },
  {
    room: "300_300",
    requires: [["quest:isles.1"]],
    receive: ["quest:isles.2"],
  },
  {
    room: "300_300",
    requires: [["quest:isles.5"]],
    receive: ["quest:isles.6"],
  },
  {
    room: "9.11_20",
    requires: [["quest:isles.6"]],
    receive: ["quest:isles.7"],
  },
  {
    room: "300_300",
    requires: [["quest:isles.15"]],
    receive: ["quest:isles.16"],
  },
  {
    room: "300_300",
    requires: [["quest:isles.17"]],
    receive: ["quest:isles.18"],
  },
  {
    room: "300_300",
    requires: [["quest:isles.23"]],
    receive: ["quest:isles.24"],
  },
  {
    room: "8_12",
    requires: [["quest:isles.8"]],
    receive: ["quest:isles.9"],
  },
  {
    room: "8_12",
    requires: [["quest:isles.10"]],
    receive: ["quest:isles.11"],
  },
  {
    room: "8_12",
    requires: [["quest:isles.11"]],
    receive: ["quest:isles.12"],
  },
  {
    room: "9.11_20",
    requires: [["quest:isles.12"]],
    receive: ["quest:isles.13"],
  },
  {
    room: "5_20",
    requires: [["quest:isles.13"]],
    receive: ["quest:isles.14"],
  },
  {
    room: "9_18",
    requires: [["quest:isles.9"]],
    receive: ["quest:isles.10"],
  },
  {
    room: "14_22",
    requires: [["quest:rings.14"]],
    receive: ["quest:rings.15"],
  },
  {
    room: "18_12",
    requires: [["quest:rings.16"]],
    receive: ["quest:rings.17"],
  },
  {
    room: "19_14",
    requires: [["quest:hWater.2"]],
    receive: ["quest:hWater.3"],
  },
  {
    room: "14_18",
    requires: [["quest:bBomb.10"]],
    receive: ["quest:bBomb.11"],
  },
  {
    room: "14_18",
    requires: [["quest:bBomb.11"]],
    receive: ["quest:bBomb.12"],
  },
  {
    room: "14_18",
    requires: [["quest:bBomb.25"]],
    receive: ["quest:bBomb.26"],
  },
  { room: "11_23", requires: [], receive: ["quest:dream.1"] },
  {
    room: "13_17",
    requires: [["quest:dream.1"]],
    receive: ["quest:dream.2"],
  },
  {
    room: "13_17",
    requires: [["quest:dream.11"]],
    receive: ["quest:dream.12"],
  },
  {
    room: "20_20",
    requires: [["quest:dream.12", "area:4"]],
    receive: ["quest:dream.13"],
  },
  {
    room: "13_17",
    requires: [["quest:dream.13"]],
    receive: ["quest:dream.14"],
  },
  {
    room: "13_17",
    requires: [["quest:dream.14"]],
    receive: ["quest:dream.15"],
  },
  {
    room: "15_25",
    requires: [["quest:oMan.13"]],
    receive: ["quest:oMan.14"],
  },
  {
    room: "10_23",
    requires: [["quest:oMan.10"]],
    receive: ["quest:oMan.11"],
  },
  {
    room: "10_15",
    requires: [["quest:oMan.8"]],
    receive: ["quest:oMan.9"],
  },
  {
    room: "18_15",
    requires: [["quest:oMan.7"]],
    receive: ["quest:oMan.8"],
  },
  {
    room: "10_23",
    requires: [["quest:oMan.9", "magic:cloud"]],
    receive: ["quest:oMan.10"],
  },
  {
    room: "10_15",
    requires: [["quest:oMan.6"]],
    receive: ["quest:oMan.7"],
  },
  {
    room: "11_21",
    requires: [["quest:oMan.15"]],
    receive: ["quest:oMan.16"],
  },
  {
    room: "11_21",
    requires: [["quest:oMan.11"]],
    receive: ["quest:oMan.12"],
  },
  {
    room: "17_19",
    requires: [["quest:oMan.14"]],
    receive: ["quest:oMan.15"],
  },
  {
    room: "17_19",
    requires: [["quest:oMan.21"]],
    receive: ["quest:oMan.22", "misc:bobbisPendant"],
  },
  {
    room: "17_19",
    requires: [["quest:oMan.20"]],
    receive: ["quest:oMan.21"],
  },
  {
    room: "17_19",
    requires: [["quest:oMan.12"]],
    receive: ["quest:oMan.13"],
  },
  {
    room: "19_15",
    requires: [["item:rubies#5", "weapon:sword", "item:bombs#50"]],
    receive: ["weapon:bombSword"],
  },
  {
    room: "19_15",
    requires: [
      ["item:rubies#7", "weapon:royalStaff", "loot:aScepter#3"],
    ],
    receive: ["weapon:refreshStaff"],
  },
  {
    room: "19_15",
    requires: [
      ["item:rubies#20", "weapon:warlockStaff", "loot:aAxe#5"],
    ],
    receive: ["weapon:axe"],
  },
  {
    room: "19_15",
    requires: [
      ["item:rubies#100", "weapon:sunSword", "loot:sFrag#5"],
    ],
    receive: ["weapon:soulSword"],
  },
  {
    room: "19_15",
    requires: [
      ["item:rubies#10", "armor:phantomCoat", "loot:kCrest#50"],
    ],
    receive: ["armor:shadowCoat"],
  },
  {
    room: "19_15",
    requires: [["item:rubies#80", "armor:sunArmor", "loot:sFrag#7"]],
    receive: ["armor:soulArmor"],
  },
  {
    room: "19_15",
    requires: [["loot:medallions#200"]],
    receive: ["skill:shield"],
  },
  {
    room: "20_20",
    requires: [["item:gold#5"]],
    receive: ["food:apple"],
  },
  {
    room: "20_20",
    requires: [["item:gold#1"]],
    receive: ["food:honey"],
  },
  {
    room: "20_20",
    requires: [["item:gold#15"]],
    receive: ["food:grapes"],
  },
  {
    room: "12_9",
    requires: [["item:gold#125"]],
    receive: ["food:carrot"],
  },
  {
    room: "12_9",
    requires: [["item:gold#200"]],
    receive: ["food:beefJerky"],
  },
  {
    room: "12_9",
    requires: [["item:gold#250"]],
    receive: ["food:cherries"],
  },
  {
    room: "21_20",
    requires: [["item:gold#50"]],
    receive: ["magic:slow"],
  },
  {
    room: "21_20",
    requires: [["item:gold#100"]],
    receive: ["magic:heal"],
  },
  {
    room: "21_20",
    requires: [["item:gold#200"]],
    receive: ["magic:blast"],
  },
  {
    room: "13_17",
    requires: [["item:gold#300"]],
    receive: ["magic:regen"],
  },
  {
    room: "13_17",
    requires: [["item:gold#2000"]],
    receive: ["magic:cloud"],
  },
  {
    room: "13_17",
    requires: [["item:gold#900"]],
    receive: ["magic:weak"],
  },
  {
    room: "11_9",
    requires: [
      ["item:gold#4500", "entrance.east0"],
      ["item:gold#4500", "entrance.north0"],
    ],
    receive: ["magic:refresh"],
  },
  {
    room: "11_9",
    requires: [
      ["item:gold#4000", "entrance.east0"],
      ["item:gold#4000", "entrance.north0"],
    ],
    receive: ["magic:lightning"],
  },
  {
    room: "20_20",
    requires: [["item:gold#10"]],
    receive: ["weapon:club"],
  },
  {
    room: "20_20",
    requires: [["item:gold#200"]],
    receive: ["weapon:sword"],
  },
  {
    room: "13_17",
    requires: [["item:gold#800"]],
    receive: ["weapon:royalSword"],
  },
  {
    room: "13_17",
    requires: [["item:gold#5000"]],
    receive: ["weapon:royalStaff"],
  },
  {
    room: "20_20",
    requires: [["item:gold#500"]],
    receive: ["armor:vest"],
  },
  {
    room: "20_20",
    requires: [["item:gold#300"]],
    receive: ["armor:robe"],
  },
  {
    room: "20_20",
    requires: [["item:gold#8000"]],
    receive: ["armor:iron"],
  },
  {
    room: "13_17",
    requires: [["item:gold#15000"]],
    receive: ["armor:royalArmor"],
  },
  {
    room: "13_17",
    requires: [["item:gold#7000"]],
    receive: ["armor:mysticCloak"],
  },
  {
    room: "12_9",
    requires: [["item:gold#2500"]],
    receive: ["armor:sunArmor"],
  },
  {
    room: "12_9",
    requires: [["item:gold#3500"]],
    receive: ["armor:speedVest"],
  },
  {
    room: "20_20",
    requires: [["item:gold"]],
    receive: ["weapon:dagger"],
  },
  {
    room: "200_200",
    requires: [
      ["loot:vHorn#20"],
      ["loot:cThread#30"],
      ["loot:gFeather#5"],
      ["weapon:orcBlade"],
    ],
    receive: ["weapon:twinFury"],
  },
  {
    room: "18_25",
    requires: [["loot:tBand#2"]],
    receive: ["skill:medic.1"],
  },
  {
    room: "18_25",
    requires: [["loot:tBand#2"], ["loot:cFang#5"]],
    receive: ["skill:medic.2"],
  },
  {
    room: "18_25",
    requires: [
      ["loot:tBand#2"],
      ["loot:cFang#5"],
      ["loot:mStaff#10"],
      ["loot:oCoin#20"],
    ],
    receive: ["skill:medic.3"],
  },
  {
    room: "18_25",
    requires: [
      ["loot:tBand#2"],
      ["loot:cFang#5"],
      ["loot:mStaff#10"],
      ["loot:oCoin#20"],
      ["loot:gSkin#10"],
      ["loot:dScale#10"],
    ],
    receive: ["skill:medic.4"],
  },
  {
    room: "18_25",
    requires: [
      ["loot:tBand#2"],
      ["loot:cFang#5"],
      ["loot:mStaff#10"],
      ["loot:oCoin#20"],
      ["loot:gSkin#10"],
      ["loot:dScale#10"],
      ["loot:aAxe#5"],
      ["loot:kCrest#10"],
    ],
    receive: ["skill:medic.5"],
  },
  {
    room: "18_25",
    requires: [
      ["loot:tBand#2"],
      ["loot:cFang#5"],
      ["loot:mStaff#10"],
      ["loot:oCoin#20"],
      ["loot:gSkin#10"],
      ["loot:dScale#10"],
      ["loot:aAxe#5"],
      ["loot:kCrest#10"],
      ["loot:gFeather#3"],
      ["loot:aScepter#5"],
    ],
    receive: ["skill:medic.6"],
  },
  { room: "4_24", requires: [], receive: ["food:cherries"] },
  {
    room: "18_21",
    requires: [["loot:key#1"]],
    receive: ["food:gingerBread"],
  },
  {
    room: "9_25",
    requires: [],
    receive: ["item:gold#Enum.Craft.emerald"],
  },
  {
    room: "9_25",
    requires: [["loot:emeralds"]],
    receive: ["food:elixir#1"],
  },
  {
    room: "19_20",
    requires: [["quest:pam.8"]],
    receive: ["food:steak#3"],
  },
  {
    room: "4_26",
    requires: [["quest:isles.22"]],
    receive: ["skill:tough", "quest:isles.23"],
  },
  {
    room: "20_18",
    requires: [
      ["loot:dScale#3"],
      ["loot:sFrag#5"],
      ["loot:fBone#10"],
    ],
    receive: ["item:ring of skill"],
  },
  {
    room: "14_18",
    requires: [["weapon:royalSword"]],
    receive: ["weapon:creeperCrusher"],
  },
  { room: "14_18", requires: [], receive: ["misc:misc"] },
  {
    room: "13_17",
    requires: [["armor:royalArmor"]],
    receive: ["armor:nobleArmor"],
  },
  { room: "19_16", requires: [[]], receive: ["area:14"] },
  { room: "21_20", requires: [[]], receive: ["area:0"] },
  { room: "20_20", requires: [[]], receive: ["area:0"] },
  { room: "19_20", requires: [[]], receive: ["area:1"] },
  { room: "18_20", requires: [[]], receive: ["area:1"] },
  { room: "17_20", requires: [[]], receive: ["area:1"] },
  { room: "16_20", requires: [[]], receive: ["area:3"] },
  { room: "15_20", requires: [[]], receive: ["area:3"] },
  { room: "14_20", requires: [[]], receive: ["area:3.1"] },
  { room: "13_20", requires: [[]], receive: ["area:3"] },
  { room: "12_20", requires: [[]], receive: ["area:1"] },
  { room: "11_20", requires: [[]], receive: ["area:16.1"] },
  { room: "10_20", requires: [[]], receive: ["area:16.1"] },
  { room: "9_20", requires: [[]], receive: ["area:16.1"] },
  { room: "8_20", requires: [[]], receive: ["area:16"] },
  { room: "7_20", requires: [[]], receive: ["area:16"] },
  { room: "6_20", requires: [[]], receive: ["area:16"] },
  { room: "5_20", requires: [[]], receive: ["area:16"] },
  { room: "4_20", requires: [[]], receive: ["area:16"] },
  { room: "3_20", requires: [[]], receive: ["area:16"] },
  { room: "3_21", requires: [[]], receive: ["area:16"] },
  { room: "4_21", requires: [[]], receive: ["area:16"] },
  { room: "5_21", requires: [[]], receive: ["area:16"] },
  { room: "6_21", requires: [[]], receive: ["area:16"] },
  { room: "7_21", requires: [[]], receive: ["area:16"] },
  { room: "8_21", requires: [[]], receive: ["area:8"] },
  { room: "9_21", requires: [[]], receive: ["area:3"] },
  { room: "10_21", requires: [[]], receive: ["area:16.1"] },
  { room: "11_21", requires: [[]], receive: ["area:3"] },
  { room: "12_21", requires: [[]], receive: ["area:1"] },
  { room: "13_21", requires: [[]], receive: ["area:3"] },
  { room: "14_21", requires: [[]], receive: ["area:3"] },
  { room: "15_21", requires: [[]], receive: ["area:3"] },
  { room: "16_21", requires: [[]], receive: ["area:3"] },
  { room: "17_21", requires: [[]], receive: ["area:3.3"] },
  { room: "18_21", requires: [[]], receive: ["area:1"] },
  { room: "19_21", requires: [[]], receive: ["area:1"] },
  { room: "20_21", requires: [[]], receive: ["area:3"] },
  { room: "21_21", requires: [[]], receive: ["area:0"] },
  { room: "21_22", requires: [[]], receive: ["area:2"] },
  { room: "20_22", requires: [[]], receive: ["area:2"] },
  { room: "19_22", requires: [[]], receive: ["area:15"] },
  { room: "18_22", requires: [[]], receive: ["area:1"] },
  { room: "17_22", requires: [[]], receive: ["area:3"] },
  { room: "16_22", requires: [[]], receive: ["area:3"] },
  { room: "15_22", requires: [[]], receive: ["area:2"] },
  { room: "14_22", requires: [[]], receive: ["area:2"] },
  { room: "13_22", requires: [[]], receive: ["area:3"] },
  { room: "12_22", requires: [[]], receive: ["area:3"] },
  { room: "11_22", requires: [[]], receive: ["area:2"] },
  { room: "10_22", requires: [[]], receive: ["area:8"] },
  { room: "9_22", requires: [[]], receive: ["area:8.1"] },
  { room: "8_22", requires: [[]], receive: ["area:8"] },
  { room: "7_22", requires: [[]], receive: ["area:8"] },
  { room: "7_23", requires: [[]], receive: ["area:8"] },
  { room: "6_23", requires: [[]], receive: ["area:8"] },
  { room: "5_23", requires: [[]], receive: ["area:9"] },
  { room: "4_23", requires: [[]], receive: ["area:9"] },
  { room: "3_23", requires: [[]], receive: ["area:9"] },
  { room: "3_24", requires: [[]], receive: ["area:9"] },
  { room: "4_24", requires: [[]], receive: ["area:9"] },
  { room: "5_24", requires: [[]], receive: ["area:9.1"] },
  { room: "6_24", requires: [[]], receive: ["area:8"] },
  { room: "7_24", requires: [[]], receive: ["area:8"] },
  { room: "8_24", requires: [[]], receive: ["area:8"] },
  { room: "8_23", requires: [[]], receive: ["area:8"] },
  { room: "9_23", requires: [[]], receive: ["area:8"] },
  { room: "10_23", requires: [[]], receive: ["area:2"] },
  { room: "11_23", requires: [[]], receive: ["area:2"] },
  { room: "12_23", requires: [[]], receive: ["area:2"] },
  { room: "13_23", requires: [[]], receive: ["area:2"] },
  { room: "14_23", requires: [[]], receive: ["area:2"] },
  { room: "15_23", requires: [[]], receive: ["area:2"] },
  { room: "16_23", requires: [[]], receive: ["area:2"] },
  {
    room: "17_23",
    requires: [[]],
    receive: ["area:2", "area:str up npc"],
  },
  { room: "18_23", requires: [[]], receive: ["area:2"] },
  { room: "19_23", requires: [[]], receive: ["area:2"] },
  { room: "20_23", requires: [[]], receive: ["area:2"] },
  { room: "21_23", requires: [[]], receive: ["area:2"] },
  { room: "18_25", requires: [[]], receive: ["area:2"] },
  { room: "18_24", requires: [[]], receive: ["area:2"] },
  { room: "17_24", requires: [[]], receive: ["area:2"] },
  { room: "19_24", requires: [[]], receive: ["area:2"] },
  { room: "16_24", requires: [[]], receive: ["area:2"] },
  { room: "15_24", requires: [[]], receive: ["area:2"] },
  { room: "14_24", requires: [[]], receive: ["area:13"] },
  { room: "13_24", requires: [[]], receive: ["area:13"] },
  { room: "12_24", requires: [[]], receive: ["area:2"] },
  { room: "11_24", requires: [[]], receive: ["area:2"] },
  { room: "10_24", requires: [[]], receive: ["area:8"] },
  { room: "9_24", requires: [[]], receive: ["area:8"] },
  { room: "3_25", requires: [[]], receive: ["area:9"] },
  { room: "3_26", requires: [[]], receive: ["area:9"] },
  { room: "4_25", requires: [[]], receive: ["area:9"] },
  { room: "7_25", requires: [[]], receive: ["area:8"] },
  {
    room: "8_25",
    requires: [[]],
    receive: ["area:8", "area:str up npc"],
  },
  { room: "9_25", requires: [[]], receive: ["area:8"] },
  { room: "10_25", requires: [[]], receive: ["area:8"] },
  { room: "11_25", requires: [[]], receive: ["area:8"] },
  { room: "12_25", requires: [[]], receive: ["area:13"] },
  { room: "13_25", requires: [[]], receive: ["area:13"] },
  { room: "14_25", requires: [[]], receive: ["area:13"] },
  { room: "15_25", requires: [[]], receive: ["area:2"] },
  { room: "16_25", requires: [[]], receive: ["area:2"] },
  { room: "17_25", requires: [[]], receive: ["area:2"] },
  { room: "13_26", requires: [[]], receive: ["area:13"] },
  { room: "12_26", requires: [[]], receive: ["area:13"] },
  { room: "11_26", requires: [[]], receive: ["area:13"] },
  { room: "10_26", requires: [[]], receive: ["area:13"] },
  { room: "9_26", requires: [[]], receive: ["area:8"] },
  { room: "100_100", requires: [[]], receive: ["area:17"] },
  { room: "200_200", requires: [[]], receive: ["area:17"] },
  { room: "201_200", requires: [[]], receive: ["area:17"] },
  { room: "300_300", requires: [[]], receive: ["area:17"] },
  { room: "500_500", requires: [[]], receive: ["area:1.19"] },
  { room: "500_501", requires: [[]], receive: ["area:1.19"] },
  { room: "501_501", requires: [[]], receive: ["area:1.19"] },
  { room: "501_500", requires: [[]], receive: ["area:1.19"] },
  { room: "3_19", requires: [[]], receive: ["area:16"] },
  { room: "4_19", requires: [[]], receive: ["area:16"] },
  { room: "5_19", requires: [[]], receive: ["area:16"] },
  { room: "6_19", requires: [[]], receive: ["area:16"] },
  { room: "7_19", requires: [[]], receive: ["area:16"] },
  { room: "8_19", requires: [[]], receive: ["area:5"] },
  { room: "9_19", requires: [[]], receive: ["area:5"] },
  { room: "10_19", requires: [[]], receive: ["area:5.1"] },
  {
    room: "11_19",
    requires: [[]],
    receive: ["area:16.1", "flag:10.1 code"],
  },
  { room: "12_19", requires: [[]], receive: ["area:1"] },
  { room: "13_19", requires: [[]], receive: ["area:3"] },
  { room: "14_19", requires: [[]], receive: ["area:3"] },
  { room: "15_19", requires: [[]], receive: ["area:3"] },
  { room: "16_19", requires: [[]], receive: ["area:3"] },
  { room: "17_19", requires: [[]], receive: ["area:1"] },
  { room: "18_19", requires: [[]], receive: ["area:1"] },
  { room: "18_18", requires: [[]], receive: ["area:12"] },
  { room: "19_18", requires: [[]], receive: ["area:12"] },
  { room: "20_18", requires: [[]], receive: ["area:12"] },
  { room: "21_18", requires: [[]], receive: ["area:12"] },
  { room: "17_18", requires: [[]], receive: ["area:3"] },
  { room: "16_18", requires: [[]], receive: ["area:3"] },
  { room: "15_18", requires: [[]], receive: ["area:0"] },
  { room: "14_18", requires: [[]], receive: ["area:0"] },
  { room: "13_18", requires: [[]], receive: ["area:0"] },
  {
    room: "13_18",
    requires: [["item:gold#50"]],
    receive: ["food:gingerBread"],
  },
  {
    room: "13_18",
    requires: [["item:gold#80"]],
    receive: ["food:banana"],
  },
  { room: "12_18", requires: [[]], receive: ["area:1"] },
  { room: "11_18", requires: [[]], receive: ["area:5"] },
  { room: "10_18", requires: [[]], receive: ["area:5"] },
  { room: "9_18", requires: [[]], receive: ["area:5"] },
  { room: "8_18", requires: [[]], receive: ["area:5"] },
  { room: "7_18", requires: [[]], receive: ["area:16"] },
  { room: "6_18", requires: [[]], receive: ["area:16"] },
  { room: "5_18", requires: [[]], receive: ["area:16"] },
  { room: "4_18", requires: [[]], receive: ["area:16"] },
  { room: "3_18", requires: [[]], receive: ["area:16"] },
  { room: "3_17", requires: [[]], receive: ["area:16"] },
  { room: "4_17", requires: [[]], receive: ["area:16"] },
  { room: "5_17", requires: [[]], receive: ["area:16"] },
  { room: "6_17", requires: [[]], receive: ["area:16"] },
  { room: "7_17", requires: [[]], receive: ["area:16"] },
  { room: "8_17", requires: [[]], receive: ["area:5"] },
  { room: "9_17", requires: [[]], receive: ["area:5"] },
  { room: "10_17", requires: [[]], receive: ["area:5"] },
  { room: "11_17", requires: [[]], receive: ["area:5"] },
  { room: "12_17", requires: [[]], receive: ["area:1"] },
  { room: "13_17", requires: [[]], receive: ["area:0"] },
  { room: "14_17", requires: [[]], receive: ["area:0"] },
  { room: "15_17", requires: [[]], receive: ["area:0"] },
  { room: "16_17", requires: [[]], receive: ["area:4"] },
  { room: "17_17", requires: [[]], receive: ["area:4"] },
  { room: "18_17", requires: [[]], receive: ["area:12"] },
  { room: "19_17", requires: [[]], receive: ["area:12"] },
  { room: "20_17", requires: [[]], receive: ["area:12"] },
  { room: "21_17", requires: [[]], receive: ["area:12"] },
  { room: "18_16", requires: [[]], receive: ["area:4"] },
  { room: "17_16", requires: [[]], receive: ["area:4"] },
  { room: "16_16", requires: [[]], receive: ["area:4"] },
  { room: "15_16", requires: [[]], receive: ["area:4"] },
  { room: "14_16", requires: [[]], receive: ["area:4"] },
  { room: "13_16", requires: [[]], receive: ["area:1"] },
  {
    room: "12_16",
    requires: [[]],
    receive: ["area:1", "area:str up npc"],
  },
  { room: "11_16", requires: [[]], receive: ["area:5"] },
  { room: "10_16", requires: [[]], receive: ["area:1"] },
  { room: "9_16", requires: [[]], receive: ["area:1"] },
  { room: "8_16", requires: [[]], receive: ["area:16"] },
  { room: "7_16", requires: [[]], receive: ["area:16"] },
  { room: "6_16", requires: [[]], receive: ["area:16"] },
  { room: "5_16", requires: [[]], receive: ["area:16"] },
  { room: "4_16", requires: [[]], receive: ["area:16"] },
  { room: "3_16", requires: [[]], receive: ["area:16"] },
  { room: "3_15", requires: [[]], receive: ["area:16"] },
  { room: "4_15", requires: [[]], receive: ["area:16"] },
  { room: "5_15", requires: [[]], receive: ["area:16"] },
  { room: "6_15", requires: [[]], receive: ["area:16"] },
  { room: "7_15", requires: [[]], receive: ["area:16"] },
  { room: "8_15", requires: [[]], receive: ["area:16"] },
  { room: "9_15", requires: [[]], receive: ["area:1"] },
  { room: "10_15", requires: [[]], receive: ["area:1"] },
  { room: "11_15", requires: [[]], receive: ["area:1"] },
  { room: "12_15", requires: [[]], receive: ["area:1"] },
  { room: "13_15", requires: [[]], receive: ["area:4"] },
  { room: "14_15", requires: [[]], receive: ["area:4"] },
  { room: "15_15", requires: [[]], receive: ["area:4"] },
  { room: "16_15", requires: [[]], receive: ["area:4"] },
  { room: "17_15", requires: [[]], receive: ["area:4"] },
  { room: "18_15", requires: [[]], receive: ["area:4"] },
  { room: "19_15", requires: [[]], receive: ["area:14"] },
  { room: "20_15", requires: [[]], receive: ["area:14"] },
  { room: "19_14", requires: [[]], receive: ["area:4.1"] },
  { room: "18_14", requires: [[]], receive: ["area:4.1"] },
  { room: "17_14", requires: [[]], receive: ["area:4.1"] },
  { room: "16_14", requires: [[]], receive: ["area:4"] },
  { room: "15_14", requires: [[]], receive: ["area:4"] },
  { room: "14_14", requires: [[]], receive: ["area:4"] },
  { room: "13_14", requires: [[]], receive: ["area:4"] },
  { room: "12_14", requires: [[]], receive: ["area:3"] },
  { room: "11_14", requires: [[]], receive: ["area:3"] },
  { room: "10_14", requires: [[]], receive: ["area:3"] },
  { room: "9_14", requires: [[]], receive: ["area:5"] },
  { room: "8_14", requires: [[]], receive: ["area:16"] },
  { room: "7_14", requires: [[]], receive: ["area:16"] },
  { room: "6_14", requires: [[]], receive: ["area:16"] },
  { room: "5_14", requires: [[]], receive: ["area:16"] },
  { room: "4_14", requires: [[]], receive: ["area:16"] },
  { room: "3_14", requires: [[]], receive: ["area:16"] },
  { room: "3_13", requires: [[]], receive: ["area:16"] },
  { room: "4_13", requires: [[]], receive: ["area:16"] },
  { room: "5_13", requires: [[]], receive: ["area:16"] },
  { room: "6_13", requires: [[]], receive: ["area:16"] },
  { room: "7_13", requires: [[]], receive: ["area:16"] },
  { room: "8_13", requires: [[]], receive: ["area:16"] },
  { room: "9_13", requires: [[]], receive: ["area:5"] },
  { room: "10_13", requires: [[]], receive: ["area:9"] },
  { room: "11_13", requires: [[]], receive: ["area:4"] },
  { room: "12_13", requires: [[]], receive: ["area:4"] },
  { room: "13_13", requires: [[]], receive: ["area:4"] },
  { room: "14_13", requires: [[]], receive: ["area:4"] },
  { room: "18_13", requires: [[]], receive: ["area:10"] },
  { room: "19_13", requires: [[]], receive: ["area:10"] },
  { room: "21_13", requires: [[]], receive: ["area:11"] },
  { room: "22_13", requires: [[]], receive: ["area:11"] },
  { room: "22_14", requires: [[]], receive: ["area:11"] },
  { room: "21_14", requires: [[]], receive: ["area:11"] },
  { room: "23_14", requires: [[]], receive: ["area:11"] },
  { room: "24_14", requires: [[]], receive: ["area:11"] },
  { room: "24_13", requires: [[]], receive: ["area:11"] },
  { room: "23_13", requires: [[]], receive: ["area:11"] },
  { room: "20_12", requires: [[]], receive: ["area:10"] },
  { room: "21_12", requires: [[]], receive: ["area:11"] },
  { room: "22_12", requires: [[]], receive: ["area:11"] },
  { room: "23_12", requires: [[]], receive: ["area:11"] },
  { room: "24_12", requires: [[]], receive: ["area:11"] },
  { room: "24_11", requires: [[]], receive: ["area:11"] },
  { room: "23_11", requires: [[]], receive: ["area:11"] },
  { room: "22_11", requires: [[]], receive: ["area:11"] },
  { room: "21_11", requires: [[]], receive: ["area:11"] },
  { room: "21_10", requires: [[]], receive: ["area:11"] },
  { room: "22_10", requires: [[]], receive: ["area:11"] },
  { room: "23_10", requires: [[]], receive: ["area:11"] },
  { room: "23_9", requires: [[]], receive: ["area:11.3"] },
  { room: "24_10", requires: [[]], receive: ["area:11"] },
  { room: "24_9", requires: [[]], receive: ["area:11.4"] },
  { room: "22_9", requires: [[]], receive: ["area:11.2"] },
  { room: "21_9", requires: [[]], receive: ["area:11.1"] },
  { room: "19_10", requires: [[]], receive: ["area:15"] },
  { room: "18_10", requires: [[]], receive: ["area:15"] },
  { room: "19_11", requires: [[]], receive: ["area:15"] },
  { room: "18_11", requires: [[]], receive: ["area:15"] },
  { room: "17_10", requires: [[]], receive: ["area:15"] },
  { room: "17_11", requires: [[]], receive: ["area:15"] },
  { room: "16_11", requires: [[]], receive: ["area:15"] },
  { room: "16_10", requires: [[]], receive: ["area:15"] },
  { room: "12_12", requires: [[]], receive: ["area:6"] },
  { room: "11_12", requires: [[]], receive: ["area:6"] },
  { room: "10_12", requires: [[]], receive: ["area:6"] },
  { room: "9_12", requires: [[]], receive: ["area:6"] },
  {
    room: "8_12",
    requires: [[]],
    receive: ["area:6", "area:str up npc"],
  },
  { room: "7_12", requires: [[]], receive: ["area:7"] },
  { room: "6_12", requires: [[]], receive: ["area:7.1"] },
  { room: "5_11", requires: [[]], receive: ["area:7"] },
  { room: "6_11", requires: [[]], receive: ["area:7"] },
  { room: "7_11", requires: [[]], receive: ["area:7.1"] },
  { room: "8_11", requires: [[]], receive: ["area:6"] },
  { room: "9_11", requires: [[]], receive: ["area:6"] },
  { room: "10_11", requires: [[]], receive: ["area:6"] },
  { room: "11_11", requires: [[]], receive: ["area:6"] },
  { room: "12_11", requires: [[]], receive: ["area:6"] },
  { room: "12_10", requires: [[]], receive: ["area:6"] },
  { room: "11_10", requires: [[]], receive: ["area:6"] },
  { room: "10_10", requires: [[]], receive: ["area:6"] },
  { room: "9_10", requires: [[]], receive: ["area:6"] },
  { room: "8_10", requires: [[]], receive: ["area:6"] },
  { room: "7_10", requires: [[]], receive: ["area:7.2"] },
  { room: "6_10", requires: [[]], receive: ["area:7"] },
  { room: "5_10", requires: [[]], receive: ["area:7"] },
  { room: "5_9", requires: [[]], receive: ["area:7"] },
  { room: "6_9", requires: [[]], receive: ["area:7"] },
  { room: "7_9", requires: [[]], receive: ["area:7.1"] },
  { room: "8_9", requires: [[]], receive: ["area:6"] },
  { room: "9_9", requires: [[]], receive: ["area:6"] },
  { room: "10_9", requires: [[]], receive: ["area:6"] },
  { room: "11_9", requires: [[]], receive: ["area:6.1"] },
  { room: "12_9", requires: [[]], receive: ["area:6.1"] },
  { room: "10.1_21", requires: [[]], receive: ["area:16.1"] },
  { room: "17.1_19", requires: [[]], receive: ["area:3"] },
  {
    room: "20_20",
    requires: [["area:str up npc", "loot:bClaw#13"]],
    receive: ["misc:str up npc.1", "flag:str up npc counter.1"],
  },
  {
    room: "20_20",
    requires: [
      [
        "area:str up npc",
        "loot:tBand#15",
        "flag:str up npc counter.1",
      ],
    ],
    receive: ["misc:str up npc.2", "flag:str up npc counter.2"],
  },
  {
    room: "20_20",
    requires: [
      [
        "area:str up npc",
        "loot:mStaff#12",
        "flag:str up npc counter.2",
      ],
    ],
    receive: ["misc:str up npc.3", "flag:str up npc counter.3"],
  },
  {
    room: "20_20",
    requires: [
      [
        "area:str up npc",
        "loot:fBone#10",
        "flag:str up npc counter.3",
      ],
    ],
    receive: ["misc:str up npc.4", "flag:str up npc counter.4"],
  },
  {
    room: "20_20",
    requires: [
      [
        "area:str up npc",
        "loot:cFang#15",
        "flag:str up npc counter.4",
      ],
    ],
    receive: ["misc:str up npc.5", "flag:str up npc counter.5"],
  },
  {
    room: "20_20",
    requires: [
      [
        "area:str up npc",
        "loot:oCoin#50",
        "flag:str up npc counter.5",
      ],
    ],
    receive: ["misc:str up npc.6", "flag:str up npc counter.6"],
  },
  {
    room: "20_20",
    requires: [
      [
        "area:str up npc",
        "loot:kCrest#10",
        "flag:str up npc counter.6",
      ],
    ],
    receive: ["misc:str up npc.7", "flag:str up npc counter.7"],
  },
  {
    room: "20_20",
    requires: [
      [
        "area:str up npc",
        "loot:dScale#10",
        "flag:str up npc counter.7",
      ],
    ],
    receive: ["misc:str up npc.8", "flag:str up npc counter.8"],
  },
  {
    room: "20_20",
    requires: [
      [
        "area:str up npc",
        "loot:vHorn#20",
        "flag:str up npc counter.8",
      ],
    ],
    receive: ["misc:str up npc.9", "flag:str up npc counter.9"],
  },
  {
    room: "20_20",
    requires: [
      [
        "area:str up npc",
        "loot:slamstones#10",
        "flag:str up npc counter.9",
      ],
    ],
    receive: ["misc:str up npc.10", "flag:str up npc counter.10"],
  },
  {
    room: "20_20",
    requires: [
      [
        "area:str up npc",
        "loot:shadowCrest#5",
        "flag:str up npc counter.10",
      ],
    ],
    receive: ["misc:str up npc.11", "flag:str up npc counter.11"],
  },
  { room: "14_13", requires: [[]], receive: ["area:magic upgrades"] },
  { room: "16_23", requires: [[]], receive: ["area:magic upgrades"] },
  {
    room: "20_20",
    requires: [["area:magic upgrades"]],
    receive: ["flag:magic:fire.2"],
  },
  {
    room: "12_22",
    requires: [["permit:bomb", "food:apple"]],
    receive: ["quest:curse.1"],
  },
  {
    room: "20_20",
    requires: [["area:12"], ["area:9"], ["area:13"]],
    receive: ["quest:curse.2"],
  },
  {
    room: "12_22",
    requires: [["permit:bomb", "quest:curse.2"]],
    receive: ["quest:curse.3"],
  },
  {
    room: "12_22",
    requires: [["quest:curse.3"]],
    receive: ["quest:curse.5"],
  },
  {
    room: "9_26",
    requires: [["quest:curse.6"]],
    receive: ["quest:curse.7"],
  },
  {
    room: "9_25",
    requires: [["quest:curse.5"]],
    receive: ["quest:curse.6"],
  },
  {
    room: "12_26",
    requires: [["quest:curse.7", "skill:kick", "flag:stomp code"]],
    receive: ["quest:curse.8"],
  },
  {
    room: "13_26",
    requires: [["quest:curse.8"]],
    receive: ["quest:curse.9"],
  },
  {
    room: "13_26",
    requires: [
      [
        "flag:three part code part 1",
        "flag:three part code part 2",
        "flag:three part code part 3",
        "quest:curse.9",
      ],
    ],
    receive: ["quest:curse.10"],
  },
]
